# Generated by Django 6.0.2 on 2026-03-08 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="category",
        ),
    ]
