# Generated by Django 6.0.2 on 2026-03-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_listing_current_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
