# Generated by Django 6.0.2 on 2026-03-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox_controls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoxControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(max_length=50, unique=True)),
                ('process_name', models.CharField(max_length=200)),
                ('control_description', models.TextField()),
                ('risk', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100)),
                ('effective_date', models.DateField()),
            ],
            options={
                'verbose_name': 'SOX Control',
                'verbose_name_plural': 'SOX Controls',
            },
        ),
    ]
