# Generated by Django 6.0.2 on 2026-03-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox_controls', '0002_soxcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='soxcontrol',
            name='sub_process',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
