# Generated by Django 6.0.2 on 2026-03-01 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sox_controls', '0003_soxcontrol_sub_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Business Process',
                'verbose_name_plural': 'Business Processes',
            },
        ),
        migrations.RemoveField(
            model_name='soxcontrol',
            name='process_name',
        ),
        migrations.AddField(
            model_name='soxcontrol',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='sox_controls.businessprocess'),
        ),
    ]
