# Generated by Django 6.0.1 on 2026-01-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
