name: Testing

on: [push]

jobs:
  test_project:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ADD THIS STEP: Fixes the Git 128 Error
      - name: Fix git safe directory
        run: git config --global --add safe.directory /home/runner/work/Code/Code

      - name: Run Django unit tests
        defaults:
          run:
            working-directory: lecture7/airline0
        run: |
          pip3 install django
          python3 manage.py test